### ISSUE TITLE
Error 'InvalidParameterException: Unexpected Number of Separators' When Running 'aws ecs wait tasks-stopped' Command for Document Ingestion

### ISSUE THREAD

**Issue by HamzaZammit** [aws-samples/semantic-search-aws-docs#5]
Hi @ArlindNocaj 

I have followed all the instructions mentioned in the AWS documentation folder. Everything is working fine until the last command **aws ecs wait tasks-stopped --region $REGION --cluster $ECS_CLUSTER_ARN --tasks $TASK_ARN** to ingest the documents. I executed this command in the 'infrastructure' folder, and it shows an error message: **Waiter TasksStopped failed: An error occurred (InvalidParameterException): Invalid identifier: Unexpected number of separators.**

Even when I replaced the variables **$REGION,** **$TASK_ARN,** and **$ECS_CLUSTER_ARN** with their actual values, the error disappeared, but the interface doesn't display anything when I ask a question.

![problem](https://github.com/aws-samples/semantic-search-aws-docs/assets/131246399/efdd18b4-7a5a-438e-9d4f-87210dbbdce0)

**Comment by malte-aws** [comment]
Hi @HamzaZammit,

thank you for reporting the problems. I apologize for the impact these issues have on your experience using the project.

I was able to reproduce your issues and found three that I fixed with #6. If you are curious I documented the specific issues in the pull request.

@ArlindNocaj will review and merge the pull request.

I would appreciate if you could try out the changes after merging the pull request to let us know if any issues remain.

Kind regards
Malte

**Comment by ArlindNocaj** [comment]
@HamzaZammit I merged the fix from Malte, please try out the fix and report back.

**Comment by HamzaZammit** [comment]
Hi @malte-aws @ArlindNocaj 
First of all, I would like to thank you for your quick response. Yes, the problem has been resolved, and now I can see the results. We just need to make the final adjustments and update the default AWS guide.
![MicrosoftTeams-image (1)](https://github.com/aws-samples/semantic-search-aws-docs/assets/131246399/6364d8ba-91ea-4a43-bfa5-b561b1771947)
![MicrosoftTeams-image](https://github.com/aws-samples/semantic-search-aws-docs/assets/131246399/19a3b713-845c-481b-8169-34d081dfbc8b)
